---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/image2/okm.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/106029/articles/210697/master/folder/figures/image2"
    url: "/users/106029/articles/210697/master/file/figures/image2/okm.png"
